import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hajar Aswad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} bg-[#0F172A]`}>
        {/* Header */}
        <header className="flex flex-col items-center justify-center h-screen">
          <h1 className="text-4xl font-bold text-center text-blue">
            Hajar Aswad
          </h1>
          <p className="text-xl text-center text-gray-light">
            Fullstack Developer
          </p>
          {/* <input className="focus:ring-2 focus:ring-blue-500 focus:outline-none appearance-none w-full text-sm leading-6 text-slate-900 placeholder-slate-400 rounded-md py-2 pl-10 ring-1 ring-slate-200 shadow-sm" type="text" aria-label="Filter projects" placeholder="Filter projects..."></input> */}
          <button className='bg-slate-700 text-gray-light rounded-md p-4 shadow-md inset-16'>testes</button>
        </header>

      </main>
    </>
  )
}
